import { motion } from 'motion/react'
import { Helmet } from 'react-helmet-async'
import { Link } from 'react-router-dom'
import { Breadcrumb, buildBreadcrumbSchema } from '../../components/Breadcrumb'
import { CTAButton } from '../../components/CTAButton'
import { CheckCircle2, BookOpen, Bell, CreditCard, Receipt, TrendingUp, Clock, IndianRupee, Users, ArrowRight } from 'lucide-react'

const breadcrumbItems = [
  { label: 'Home', path: '/' },
  { label: 'Guides', path: '/guides' },
  { label: 'Rent Collection Guide', path: '/guides/rent-collection-guide' },
]

const features = [
  { icon: Bell, title: 'Automated WhatsApp Reminders', desc: 'Tenants receive personalized payment reminders on WhatsApp 3 days before due date, on due date, and daily after overdue.' },
  { icon: CreditCard, title: 'UPI & Digital Payment Integration', desc: 'Accept payments via Google Pay, PhonePe, Paytm, net banking, and cards. Every transaction is recorded automatically.' },
  { icon: Receipt, title: 'Instant Digital Receipts', desc: 'Generate and deliver digital rent receipts automatically after each payment. Tenants can download receipts anytime.' },
  { icon: TrendingUp, title: 'Real-Time Payment Dashboard', desc: 'See who has paid, who hasn\'t, and how much is pending — all from one screen updated in real-time.' },
  { icon: Clock, title: 'Late Payment Escalation', desc: 'Automated escalation sequence: reminder → warning → final notice. Customizable timing and messaging for each stage.' },
  { icon: IndianRupee, title: 'Monthly Reconciliation Reports', desc: 'Auto-generated monthly reports showing collected vs pending rent, payment methods used, and transaction history.' },
]

const faqs = [
  { q: 'How does automated rent collection work?', a: 'MY PG sends automatic WhatsApp reminders to tenants before the due date. Tenants can pay directly through UPI (Google Pay, PhonePe, Paytm), net banking, or debit/credit cards. After payment, a digital receipt is generated instantly. The owner sees all payments updated in real-time on the dashboard.' },
  { q: 'Can I accept UPI payments for PG rent?', a: 'Yes, MY PG integrates with all major UPI apps including Google Pay, PhonePe, and Paytm. Tenants receive payment links via WhatsApp and can complete the payment in seconds. All UPI transactions are recorded with the transaction ID for audit purposes.' },
  { q: 'What happens when a tenant is late on rent?', a: 'MY PG automatically escalates reminders based on your configured schedule. Typically: Day 0 (due date) — gentle reminder, Day 3 — follow-up with late fee notification, Day 7 — final notice with escalation warning. Owners can also manually trigger reminders anytime.' },
  { q: 'Are digital rent receipts legally valid?', a: 'Yes, digital rent receipts generated by MY PG are legally valid as they include owner details, tenant details, property address, rent amount, payment date, transaction ID, and a unique receipt number. They can be used for tax filing, IT returns, and HRA claims.' },
  { q: 'How much time does rent collection software save?', a: 'PG owners save an average of 10-15 hours per week by switching from manual collection to automated rent collection software. This includes time spent on reminders, receipt generation, reconciliation, and follow-ups.' },
  { q: 'Can I track partial payments?', a: 'Yes, MY PG supports partial payments. If a tenant pays only part of the rent, the system records the partial payment and continues to track the remaining balance. Owners and tenants both see the outstanding amount clearly.' },
]

export function RentCollectionGuide() {
  return (
    <>
      <Helmet>
        <title>Rent Collection for PG Owners: Complete Guide to Automating Payments (2026) | MY PG</title>
        <meta name="description" content="Learn how to automate rent collection for your PG in India. Complete guide covering UPI payments, WhatsApp reminders, digital receipts, and late payment recovery. Start collecting rent automatically." />
        <link rel="canonical" href="https://manageyourpg.com/guides/rent-collection-guide" />
        <meta property="og:title" content="Rent Collection for PG Owners: Complete Guide to Automating Payments (2026)" />
        <meta property="og:description" content="Learn how to automate rent collection for your PG. UPI payments, WhatsApp reminders, digital receipts, and more." />
        <meta name="robots" content="index, follow" />
        <script type="application/ld+json">
          {JSON.stringify({
            '@context': 'https://schema.org',
            '@type': 'Article',
            headline: 'Rent Collection for PG Owners: Complete Guide to Automating Payments (2026)',
            description: 'Learn how to automate rent collection for your PG in India.',
            author: { '@type': 'Organization', name: 'MY PG Solutions' },
            publisher: { '@type': 'Organization', name: 'MY PG Solutions', logo: { '@type': 'ImageObject', url: 'https://manageyourpg.com/favicon.png' } },
            datePublished: '2026-05-10',
            dateModified: '2026-05-10',
          })}
        </script>
        <script type="application/ld+json">{JSON.stringify(buildBreadcrumbSchema(breadcrumbItems))}</script>
      </Helmet>

      <section className="py-12 md:py-20 bg-gradient-to-br from-gray-50 to-orange-50">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <Breadcrumb items={breadcrumbItems} />

          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
            <div className="inline-flex items-center gap-2 mb-4 px-4 py-2 bg-orange-100 text-orange-700 rounded-full">
              <BookOpen className="w-4 h-4" />
              Complete Guide
            </div>
            <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4">
              Rent Collection for PG Owners:{' '}
              <span className="bg-gradient-to-r from-orange-600 to-red-600 bg-clip-text text-transparent">
                Complete Guide to Automating Payments
              </span>{' '}
              (2026)
            </h1>
            <p className="text-lg text-gray-600 mb-8">
              The definitive guide to automating rent collection for your PG accommodation in India. Learn how to eliminate late payments, reduce manual work, and improve cash flow with rent collection software.
            </p>
          </motion.div>

          <div className="bg-gradient-to-br from-[#1a1a4e] to-[#1e3a8a] rounded-2xl p-6 md:p-8 text-white mb-12">
            <p className="text-blue-100 text-sm font-semibold uppercase tracking-wider mb-2">In This Guide</p>
            <ul className="space-y-2">
              <li><a href="#problem" className="text-white hover:text-blue-200 flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-blue-300" /> The Rent Collection Problem for PG Owners</a></li>
              <li><a href="#solution" className="text-white hover:text-blue-200 flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-blue-300" /> How Automated Rent Collection Works</a></li>
              <li><a href="#features" className="text-white hover:text-blue-200 flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-blue-300" /> 6 Essential Features</a></li>
              <li><a href="#roi" className="text-white hover:text-blue-200 flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-blue-300" /> Time & Cost Savings</a></li>
              <li><a href="#comparison" className="text-white hover:text-blue-200 flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-blue-300" /> Automated vs Manual Collection</a></li>
              <li><a href="#faq" className="text-white hover:text-blue-200 flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-blue-300" /> FAQ</a></li>
            </ul>
          </div>

          <div className="space-y-12">
            <section id="problem" className="scroll-mt-24">
              <h2 className="text-2xl md:text-3xl font-bold text-gray-900 mb-4">The Rent Collection Problem for PG Owners</h2>
              <p className="text-gray-700 leading-relaxed mb-4">
                Rent collection is the most time-consuming and stressful part of running a PG. Owners juggle multiple payment methods — cash, UPI, bank transfers — and spend hours each week sending reminders, tracking who has paid, and reconciling accounts. Disputes with tenants about payment history are common when records are maintained manually.
              </p>
              <p className="text-gray-700 leading-relaxed">
                The average PG owner spends 5-7 hours per week just on rent collection activities. For owners with multiple properties, this scales linearly. Late payments are a persistent problem — without automated reminders, 30-40% of tenants pay late, affecting the owner's cash flow and adding stress to the owner-tenant relationship.
              </p>
            </section>

            <section id="solution" className="scroll-mt-24">
              <h2 className="text-2xl md:text-3xl font-bold text-gray-900 mb-4">How Automated Rent Collection Works</h2>
              <div className="grid md:grid-cols-3 gap-4 mb-6">
                <div className="bg-blue-50 rounded-xl p-5 border border-blue-100 text-center">
                  <div className="text-3xl font-bold text-[#1a1a4e] mb-2">1</div>
                  <h3 className="font-bold text-gray-900 mb-1">Set It Up</h3>
                  <p className="text-sm text-gray-600">Configure rent amounts, due dates, reminder schedules, and late fees for each tenant or room.</p>
                </div>
                <div className="bg-blue-50 rounded-xl p-5 border border-blue-100 text-center">
                  <div className="text-3xl font-bold text-[#1a1a4e] mb-2">2</div>
                  <h3 className="font-bold text-gray-900 mb-1">Automate It</h3>
                  <p className="text-sm text-gray-600">MY PG sends WhatsApp reminders, tracks payments, generates receipts, and escalates late payments automatically.</p>
                </div>
                <div className="bg-blue-50 rounded-xl p-5 border border-blue-100 text-center">
                  <div className="text-3xl font-bold text-[#1a1a4e] mb-2">3</div>
                  <h3 className="font-bold text-gray-900 mb-1">Monitor It</h3>
                  <p className="text-sm text-gray-600">View real-time payment status, download monthly reconciliation reports, and export data for your CA.</p>
                </div>
              </div>
            </section>

            <section id="features" className="scroll-mt-24">
              <h2 className="text-2xl md:text-3xl font-bold text-gray-900 mb-4">6 Essential Rent Collection Features</h2>
              <div className="grid md:grid-cols-2 gap-4">
                {features.map(f => (
                  <div key={f.title} className="bg-white rounded-xl p-5 border border-gray-200">
                    <div className="flex items-start gap-3">
                      <f.icon className="w-5 h-5 text-[#1a1a4e] mt-0.5 flex-shrink-0" />
                      <div>
                        <h3 className="font-bold text-gray-900">{f.title}</h3>
                        <p className="text-sm text-gray-600 mt-1">{f.desc}</p>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
              <div className="mt-6 text-center">
                <Link to="/features/rent-collection-software" className="text-[#1a1a4e] font-medium hover:underline inline-flex items-center gap-1">
                  Learn more about Rent Collection Software <ArrowRight className="w-4 h-4" />
                </Link>
              </div>
            </section>

            <section id="roi" className="scroll-mt-24">
              <h2 className="text-2xl md:text-3xl font-bold text-gray-900 mb-4">Time & Cost Savings</h2>
              <div className="grid md:grid-cols-3 gap-4 mb-6">
                <div className="bg-green-50 rounded-xl p-5 border border-green-100 text-center">
                  <p className="text-sm text-green-600 font-semibold uppercase">Time Saved</p>
                  <p className="text-3xl font-bold text-gray-900 my-1">10-15</p>
                  <p className="text-sm text-gray-600">hours per week</p>
                </div>
                <div className="bg-green-50 rounded-xl p-5 border border-green-100 text-center">
                  <p className="text-sm text-green-600 font-semibold uppercase">Late Payments</p>
                  <p className="text-3xl font-bold text-gray-900 my-1">80%</p>
                  <p className="text-sm text-gray-600">reduction with automation</p>
                </div>
                <div className="bg-green-50 rounded-xl p-5 border border-green-100 text-center">
                  <p className="text-sm text-green-600 font-semibold uppercase">Monthly Cost</p>
                  <p className="text-3xl font-bold text-gray-900 my-1">₹499</p>
                  <p className="text-sm text-gray-600">for MY PG subscription</p>
                </div>
              </div>
              <div className="bg-blue-50 rounded-xl p-5 border border-blue-100">
                <h3 className="font-bold text-[#1a1a4e] mb-2">ROI Example</h3>
                <p className="text-gray-700 text-sm">A PG owner with 20 tenants saves 12 hours/week on rent collection. At a conservative ₹200/hour, that's ₹9,600/month in time value. MY PG costs ₹499/month. <strong className="text-green-700">Net monthly savings: ₹9,101 and 12 hours of free time.</strong></p>
              </div>
            </section>

            <section id="comparison" className="scroll-mt-24">
              <h2 className="text-2xl md:text-3xl font-bold text-gray-900 mb-4">Automated vs Manual Rent Collection</h2>
              <div className="overflow-x-auto">
                <table className="w-full border-collapse text-sm">
                  <thead>
                    <tr className="border-b-2 border-gray-200">
                      <th className="text-left py-3 px-4 font-bold text-gray-900 bg-gray-50 rounded-l-lg">Aspect</th>
                      <th className="text-left py-3 px-4 font-bold text-green-700 bg-green-50">With Automation</th>
                      <th className="text-left py-3 px-4 font-bold text-red-600 bg-red-50 rounded-r-lg">Manual Process</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr className="border-b border-gray-100"><td className="py-3 px-4 font-medium">Reminders</td><td className="py-3 px-4 text-green-700">Automatic WhatsApp/SMS</td><td className="py-3 px-4 text-red-600">Manual messages to each tenant</td></tr>
                    <tr className="border-b border-gray-100"><td className="py-3 px-4 font-medium">Receipts</td><td className="py-3 px-4 text-green-700">Digital, instant delivery</td><td className="py-3 px-4 text-red-600">Handwritten, delayed</td></tr>
                    <tr className="border-b border-gray-100"><td className="py-3 px-4 font-medium">Payment tracking</td><td className="py-3 px-4 text-green-700">Real-time dashboard</td><td className="py-3 px-4 text-red-600">Spreadsheet or notebook</td></tr>
                    <tr className="border-b border-gray-100"><td className="py-3 px-4 font-medium">Late payment follow-up</td><td className="py-3 px-4 text-green-700">Automated escalation</td><td className="py-3 px-4 text-red-600">Manual calls/messages</td></tr>
                    <tr className="border-b border-gray-100"><td className="py-3 px-4 font-medium">Monthly reports</td><td className="py-3 px-4 text-green-700">Auto-generated</td><td className="py-3 px-4 text-red-600">Manual calculation</td></tr>
                    <tr className="border-b border-gray-100"><td className="py-3 px-4 font-medium">Time per week</td><td className="py-3 px-4 text-green-700">30 minutes</td><td className="py-3 px-4 text-red-600">5-7 hours</td></tr>
                  </tbody>
                </table>
              </div>
            </section>
          </div>

          <section id="faq" className="scroll-mt-24 mt-12">
            <h2 className="text-2xl md:text-3xl font-bold text-gray-900 mb-6">Frequently Asked Questions</h2>
            <div className="space-y-4">
              {faqs.map(faq => (
                <details key={faq.q} className="group bg-white rounded-xl border border-gray-200 overflow-hidden">
                  <summary className="px-6 py-4 font-medium text-gray-900 cursor-pointer hover:bg-gray-50 flex items-center justify-between">
                    {faq.q}
                    <svg className="w-5 h-5 text-gray-400 group-open:rotate-180 transition-transform flex-shrink-0 ml-4" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="6 9 12 15 18 9" /></svg>
                  </summary>
                  <div className="px-6 pb-4 text-gray-600 leading-relaxed">{faq.a}</div>
                </details>
              ))}
            </div>
          </section>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="mt-12 text-center"
          >
            <div className="bg-gradient-to-br from-orange-600 to-red-600 rounded-2xl p-8 md:p-12 shadow-2xl">
              <h2 className="text-2xl md:text-3xl font-bold text-white mb-4">Start Collecting Rent Automatically Today</h2>
              <p className="text-orange-100 mb-6 max-w-lg mx-auto">Free 7-day trial. No credit card. Full access to all rent collection features.</p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <CTAButton variant="secondary" href="/#contact">Start Free Trial</CTAButton>
                <CTAButton variant="ghost" href="/features/rent-collection-software">View Feature Details</CTAButton>
              </div>
            </div>
          </motion.div>
        </div>
      </section>
    </>
  )
}
